package com.kuaizhan.dao.mapper.auto;

import com.kuaizhan.pojo.po.auto.SiteWeixin;
import com.kuaizhan.pojo.po.auto.SiteWeixinExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SiteWeixinMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table site_weixin
     *
     * @mbggenerated Tue Jun 06 15:21:07 CST 2017
     */
    int countByExample(SiteWeixinExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table site_weixin
     *
     * @mbggenerated Tue Jun 06 15:21:07 CST 2017
     */
    int deleteByExample(SiteWeixinExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table site_weixin
     *
     * @mbggenerated Tue Jun 06 15:21:07 CST 2017
     */
    int deleteByPrimaryKey(Long weixinAppid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table site_weixin
     *
     * @mbggenerated Tue Jun 06 15:21:07 CST 2017
     */
    int insert(SiteWeixin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table site_weixin
     *
     * @mbggenerated Tue Jun 06 15:21:07 CST 2017
     */
    int insertSelective(SiteWeixin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table site_weixin
     *
     * @mbggenerated Tue Jun 06 15:21:07 CST 2017
     */
    List<SiteWeixin> selectByExampleWithBLOBs(SiteWeixinExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table site_weixin
     *
     * @mbggenerated Tue Jun 06 15:21:07 CST 2017
     */
    List<SiteWeixin> selectByExample(SiteWeixinExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table site_weixin
     *
     * @mbggenerated Tue Jun 06 15:21:07 CST 2017
     */
    SiteWeixin selectByPrimaryKey(Long weixinAppid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table site_weixin
     *
     * @mbggenerated Tue Jun 06 15:21:07 CST 2017
     */
    int updateByExampleSelective(@Param("record") SiteWeixin record, @Param("example") SiteWeixinExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table site_weixin
     *
     * @mbggenerated Tue Jun 06 15:21:07 CST 2017
     */
    int updateByExampleWithBLOBs(@Param("record") SiteWeixin record, @Param("example") SiteWeixinExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table site_weixin
     *
     * @mbggenerated Tue Jun 06 15:21:07 CST 2017
     */
    int updateByExample(@Param("record") SiteWeixin record, @Param("example") SiteWeixinExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table site_weixin
     *
     * @mbggenerated Tue Jun 06 15:21:07 CST 2017
     */
    int updateByPrimaryKeySelective(SiteWeixin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table site_weixin
     *
     * @mbggenerated Tue Jun 06 15:21:07 CST 2017
     */
    int updateByPrimaryKeyWithBLOBs(SiteWeixin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table site_weixin
     *
     * @mbggenerated Tue Jun 06 15:21:07 CST 2017
     */
    int updateByPrimaryKey(SiteWeixin record);
}