package com.kuaizhan.dao.mapper.auto;

import com.kuaizhan.pojo.po.auto.WeixinMenuItem;
import com.kuaizhan.pojo.po.auto.WeixinMenuItemExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface WeixinMenuItemMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weixin_menu_item
     *
     * @mbggenerated Thu May 25 17:18:21 CST 2017
     */
    int countByExample(WeixinMenuItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weixin_menu_item
     *
     * @mbggenerated Thu May 25 17:18:21 CST 2017
     */
    int deleteByExample(WeixinMenuItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weixin_menu_item
     *
     * @mbggenerated Thu May 25 17:18:21 CST 2017
     */
    int deleteByPrimaryKey(Long menuKey);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weixin_menu_item
     *
     * @mbggenerated Thu May 25 17:18:21 CST 2017
     */
    int insert(WeixinMenuItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weixin_menu_item
     *
     * @mbggenerated Thu May 25 17:18:21 CST 2017
     */
    int insertSelective(WeixinMenuItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weixin_menu_item
     *
     * @mbggenerated Thu May 25 17:18:21 CST 2017
     */
    List<WeixinMenuItem> selectByExampleWithBLOBs(WeixinMenuItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weixin_menu_item
     *
     * @mbggenerated Thu May 25 17:18:21 CST 2017
     */
    List<WeixinMenuItem> selectByExample(WeixinMenuItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weixin_menu_item
     *
     * @mbggenerated Thu May 25 17:18:21 CST 2017
     */
    WeixinMenuItem selectByPrimaryKey(Long menuKey);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weixin_menu_item
     *
     * @mbggenerated Thu May 25 17:18:21 CST 2017
     */
    int updateByExampleSelective(@Param("record") WeixinMenuItem record, @Param("example") WeixinMenuItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weixin_menu_item
     *
     * @mbggenerated Thu May 25 17:18:21 CST 2017
     */
    int updateByExampleWithBLOBs(@Param("record") WeixinMenuItem record, @Param("example") WeixinMenuItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weixin_menu_item
     *
     * @mbggenerated Thu May 25 17:18:21 CST 2017
     */
    int updateByExample(@Param("record") WeixinMenuItem record, @Param("example") WeixinMenuItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weixin_menu_item
     *
     * @mbggenerated Thu May 25 17:18:21 CST 2017
     */
    int updateByPrimaryKeySelective(WeixinMenuItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weixin_menu_item
     *
     * @mbggenerated Thu May 25 17:18:21 CST 2017
     */
    int updateByPrimaryKeyWithBLOBs(WeixinMenuItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weixin_menu_item
     *
     * @mbggenerated Thu May 25 17:18:21 CST 2017
     */
    int updateByPrimaryKey(WeixinMenuItem record);
}