package com.kuaizhan.kzweixin.pojo.po.auto;

public class SiteWeixin {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column site_weixin.weixin_appid
     *
     * @mbggenerated Fri Jun 09 11:46:43 CST 2017
     */
    private Long weixinAppid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column site_weixin.site_id
     *
     * @mbggenerated Fri Jun 09 11:46:43 CST 2017
     */
    private Long siteId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column site_weixin.access_token
     *
     * @mbggenerated Fri Jun 09 11:46:43 CST 2017
     */
    private String accessToken;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column site_weixin.refresh_token
     *
     * @mbggenerated Fri Jun 09 11:46:43 CST 2017
     */
    private String refreshToken;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column site_weixin.expires_time
     *
     * @mbggenerated Fri Jun 09 11:46:43 CST 2017
     */
    private Integer expiresTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column site_weixin.app_id
     *
     * @mbggenerated Fri Jun 09 11:46:43 CST 2017
     */
    private String appId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column site_weixin.app_secret
     *
     * @mbggenerated Fri Jun 09 11:46:43 CST 2017
     */
    private String appSecret;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column site_weixin.func_info_json
     *
     * @mbggenerated Fri Jun 09 11:46:43 CST 2017
     */
    private String funcInfoJson;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column site_weixin.nick_name
     *
     * @mbggenerated Fri Jun 09 11:46:43 CST 2017
     */
    private String nickName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column site_weixin.head_img
     *
     * @mbggenerated Fri Jun 09 11:46:43 CST 2017
     */
    private String headImg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column site_weixin.service_type
     *
     * @mbggenerated Fri Jun 09 11:46:43 CST 2017
     */
    private Integer serviceType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column site_weixin.verify_type
     *
     * @mbggenerated Fri Jun 09 11:46:43 CST 2017
     */
    private Integer verifyType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column site_weixin.user_name
     *
     * @mbggenerated Fri Jun 09 11:46:43 CST 2017
     */
    private String userName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column site_weixin.alias
     *
     * @mbggenerated Fri Jun 09 11:46:43 CST 2017
     */
    private String alias;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column site_weixin.business_info_json
     *
     * @mbggenerated Fri Jun 09 11:46:43 CST 2017
     */
    private String businessInfoJson;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column site_weixin.qrcode_url
     *
     * @mbggenerated Fri Jun 09 11:46:43 CST 2017
     */
    private String qrcodeUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column site_weixin.qrcode_url_kz
     *
     * @mbggenerated Fri Jun 09 11:46:43 CST 2017
     */
    private String qrcodeUrlKz;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column site_weixin.interest_json
     *
     * @mbggenerated Fri Jun 09 11:46:43 CST 2017
     */
    private String interestJson;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column site_weixin.advanced_func_info_json
     *
     * @mbggenerated Fri Jun 09 11:46:43 CST 2017
     */
    private String advancedFuncInfoJson;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column site_weixin.preview_open_id
     *
     * @mbggenerated Fri Jun 09 11:46:43 CST 2017
     */
    private String previewOpenId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column site_weixin.bind_time
     *
     * @mbggenerated Fri Jun 09 11:46:43 CST 2017
     */
    private Integer bindTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column site_weixin.unbind_time
     *
     * @mbggenerated Fri Jun 09 11:46:43 CST 2017
     */
    private Integer unbindTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column site_weixin.is_del
     *
     * @mbggenerated Fri Jun 09 11:46:43 CST 2017
     */
    private Integer isDel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column site_weixin.create_time
     *
     * @mbggenerated Fri Jun 09 11:46:43 CST 2017
     */
    private Integer createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column site_weixin.update_time
     *
     * @mbggenerated Fri Jun 09 11:46:43 CST 2017
     */
    private Integer updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column site_weixin.user_id
     *
     * @mbggenerated Fri Jun 09 11:46:43 CST 2017
     */
    private Long userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column site_weixin.menu_json
     *
     * @mbggenerated Fri Jun 09 11:46:43 CST 2017
     */
    private String menuJson;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column site_weixin.weixin_appid
     *
     * @return the value of site_weixin.weixin_appid
     *
     * @mbggenerated Fri Jun 09 11:46:43 CST 2017
     */
    public Long getWeixinAppid() {
        return weixinAppid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column site_weixin.weixin_appid
     *
     * @param weixinAppid the value for site_weixin.weixin_appid
     *
     * @mbggenerated Fri Jun 09 11:46:43 CST 2017
     */
    public void setWeixinAppid(Long weixinAppid) {
        this.weixinAppid = weixinAppid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column site_weixin.site_id
     *
     * @return the value of site_weixin.site_id
     *
     * @mbggenerated Fri Jun 09 11:46:43 CST 2017
     */
    public Long getSiteId() {
        return siteId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column site_weixin.site_id
     *
     * @param siteId the value for site_weixin.site_id
     *
     * @mbggenerated Fri Jun 09 11:46:43 CST 2017
     */
    public void setSiteId(Long siteId) {
        this.siteId = siteId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column site_weixin.access_token
     *
     * @return the value of site_weixin.access_token
     *
     * @mbggenerated Fri Jun 09 11:46:43 CST 2017
     */
    public String getAccessToken() {
        return accessToken;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column site_weixin.access_token
     *
     * @param accessToken the value for site_weixin.access_token
     *
     * @mbggenerated Fri Jun 09 11:46:43 CST 2017
     */
    public void setAccessToken(String accessToken) {
        this.accessToken = accessToken;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column site_weixin.refresh_token
     *
     * @return the value of site_weixin.refresh_token
     *
     * @mbggenerated Fri Jun 09 11:46:43 CST 2017
     */
    public String getRefreshToken() {
        return refreshToken;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column site_weixin.refresh_token
     *
     * @param refreshToken the value for site_weixin.refresh_token
     *
     * @mbggenerated Fri Jun 09 11:46:43 CST 2017
     */
    public void setRefreshToken(String refreshToken) {
        this.refreshToken = refreshToken;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column site_weixin.expires_time
     *
     * @return the value of site_weixin.expires_time
     *
     * @mbggenerated Fri Jun 09 11:46:43 CST 2017
     */
    public Integer getExpiresTime() {
        return expiresTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column site_weixin.expires_time
     *
     * @param expiresTime the value for site_weixin.expires_time
     *
     * @mbggenerated Fri Jun 09 11:46:43 CST 2017
     */
    public void setExpiresTime(Integer expiresTime) {
        this.expiresTime = expiresTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column site_weixin.app_id
     *
     * @return the value of site_weixin.app_id
     *
     * @mbggenerated Fri Jun 09 11:46:43 CST 2017
     */
    public String getAppId() {
        return appId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column site_weixin.app_id
     *
     * @param appId the value for site_weixin.app_id
     *
     * @mbggenerated Fri Jun 09 11:46:43 CST 2017
     */
    public void setAppId(String appId) {
        this.appId = appId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column site_weixin.app_secret
     *
     * @return the value of site_weixin.app_secret
     *
     * @mbggenerated Fri Jun 09 11:46:43 CST 2017
     */
    public String getAppSecret() {
        return appSecret;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column site_weixin.app_secret
     *
     * @param appSecret the value for site_weixin.app_secret
     *
     * @mbggenerated Fri Jun 09 11:46:43 CST 2017
     */
    public void setAppSecret(String appSecret) {
        this.appSecret = appSecret;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column site_weixin.func_info_json
     *
     * @return the value of site_weixin.func_info_json
     *
     * @mbggenerated Fri Jun 09 11:46:43 CST 2017
     */
    public String getFuncInfoJson() {
        return funcInfoJson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column site_weixin.func_info_json
     *
     * @param funcInfoJson the value for site_weixin.func_info_json
     *
     * @mbggenerated Fri Jun 09 11:46:43 CST 2017
     */
    public void setFuncInfoJson(String funcInfoJson) {
        this.funcInfoJson = funcInfoJson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column site_weixin.nick_name
     *
     * @return the value of site_weixin.nick_name
     *
     * @mbggenerated Fri Jun 09 11:46:43 CST 2017
     */
    public String getNickName() {
        return nickName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column site_weixin.nick_name
     *
     * @param nickName the value for site_weixin.nick_name
     *
     * @mbggenerated Fri Jun 09 11:46:43 CST 2017
     */
    public void setNickName(String nickName) {
        this.nickName = nickName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column site_weixin.head_img
     *
     * @return the value of site_weixin.head_img
     *
     * @mbggenerated Fri Jun 09 11:46:43 CST 2017
     */
    public String getHeadImg() {
        return headImg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column site_weixin.head_img
     *
     * @param headImg the value for site_weixin.head_img
     *
     * @mbggenerated Fri Jun 09 11:46:43 CST 2017
     */
    public void setHeadImg(String headImg) {
        this.headImg = headImg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column site_weixin.service_type
     *
     * @return the value of site_weixin.service_type
     *
     * @mbggenerated Fri Jun 09 11:46:43 CST 2017
     */
    public Integer getServiceType() {
        return serviceType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column site_weixin.service_type
     *
     * @param serviceType the value for site_weixin.service_type
     *
     * @mbggenerated Fri Jun 09 11:46:43 CST 2017
     */
    public void setServiceType(Integer serviceType) {
        this.serviceType = serviceType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column site_weixin.verify_type
     *
     * @return the value of site_weixin.verify_type
     *
     * @mbggenerated Fri Jun 09 11:46:43 CST 2017
     */
    public Integer getVerifyType() {
        return verifyType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column site_weixin.verify_type
     *
     * @param verifyType the value for site_weixin.verify_type
     *
     * @mbggenerated Fri Jun 09 11:46:43 CST 2017
     */
    public void setVerifyType(Integer verifyType) {
        this.verifyType = verifyType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column site_weixin.user_name
     *
     * @return the value of site_weixin.user_name
     *
     * @mbggenerated Fri Jun 09 11:46:43 CST 2017
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column site_weixin.user_name
     *
     * @param userName the value for site_weixin.user_name
     *
     * @mbggenerated Fri Jun 09 11:46:43 CST 2017
     */
    public void setUserName(String userName) {
        this.userName = userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column site_weixin.alias
     *
     * @return the value of site_weixin.alias
     *
     * @mbggenerated Fri Jun 09 11:46:43 CST 2017
     */
    public String getAlias() {
        return alias;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column site_weixin.alias
     *
     * @param alias the value for site_weixin.alias
     *
     * @mbggenerated Fri Jun 09 11:46:43 CST 2017
     */
    public void setAlias(String alias) {
        this.alias = alias;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column site_weixin.business_info_json
     *
     * @return the value of site_weixin.business_info_json
     *
     * @mbggenerated Fri Jun 09 11:46:43 CST 2017
     */
    public String getBusinessInfoJson() {
        return businessInfoJson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column site_weixin.business_info_json
     *
     * @param businessInfoJson the value for site_weixin.business_info_json
     *
     * @mbggenerated Fri Jun 09 11:46:43 CST 2017
     */
    public void setBusinessInfoJson(String businessInfoJson) {
        this.businessInfoJson = businessInfoJson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column site_weixin.qrcode_url
     *
     * @return the value of site_weixin.qrcode_url
     *
     * @mbggenerated Fri Jun 09 11:46:43 CST 2017
     */
    public String getQrcodeUrl() {
        return qrcodeUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column site_weixin.qrcode_url
     *
     * @param qrcodeUrl the value for site_weixin.qrcode_url
     *
     * @mbggenerated Fri Jun 09 11:46:43 CST 2017
     */
    public void setQrcodeUrl(String qrcodeUrl) {
        this.qrcodeUrl = qrcodeUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column site_weixin.qrcode_url_kz
     *
     * @return the value of site_weixin.qrcode_url_kz
     *
     * @mbggenerated Fri Jun 09 11:46:43 CST 2017
     */
    public String getQrcodeUrlKz() {
        return qrcodeUrlKz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column site_weixin.qrcode_url_kz
     *
     * @param qrcodeUrlKz the value for site_weixin.qrcode_url_kz
     *
     * @mbggenerated Fri Jun 09 11:46:43 CST 2017
     */
    public void setQrcodeUrlKz(String qrcodeUrlKz) {
        this.qrcodeUrlKz = qrcodeUrlKz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column site_weixin.interest_json
     *
     * @return the value of site_weixin.interest_json
     *
     * @mbggenerated Fri Jun 09 11:46:43 CST 2017
     */
    public String getInterestJson() {
        return interestJson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column site_weixin.interest_json
     *
     * @param interestJson the value for site_weixin.interest_json
     *
     * @mbggenerated Fri Jun 09 11:46:43 CST 2017
     */
    public void setInterestJson(String interestJson) {
        this.interestJson = interestJson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column site_weixin.advanced_func_info_json
     *
     * @return the value of site_weixin.advanced_func_info_json
     *
     * @mbggenerated Fri Jun 09 11:46:43 CST 2017
     */
    public String getAdvancedFuncInfoJson() {
        return advancedFuncInfoJson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column site_weixin.advanced_func_info_json
     *
     * @param advancedFuncInfoJson the value for site_weixin.advanced_func_info_json
     *
     * @mbggenerated Fri Jun 09 11:46:43 CST 2017
     */
    public void setAdvancedFuncInfoJson(String advancedFuncInfoJson) {
        this.advancedFuncInfoJson = advancedFuncInfoJson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column site_weixin.preview_open_id
     *
     * @return the value of site_weixin.preview_open_id
     *
     * @mbggenerated Fri Jun 09 11:46:43 CST 2017
     */
    public String getPreviewOpenId() {
        return previewOpenId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column site_weixin.preview_open_id
     *
     * @param previewOpenId the value for site_weixin.preview_open_id
     *
     * @mbggenerated Fri Jun 09 11:46:43 CST 2017
     */
    public void setPreviewOpenId(String previewOpenId) {
        this.previewOpenId = previewOpenId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column site_weixin.bind_time
     *
     * @return the value of site_weixin.bind_time
     *
     * @mbggenerated Fri Jun 09 11:46:43 CST 2017
     */
    public Integer getBindTime() {
        return bindTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column site_weixin.bind_time
     *
     * @param bindTime the value for site_weixin.bind_time
     *
     * @mbggenerated Fri Jun 09 11:46:43 CST 2017
     */
    public void setBindTime(Integer bindTime) {
        this.bindTime = bindTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column site_weixin.unbind_time
     *
     * @return the value of site_weixin.unbind_time
     *
     * @mbggenerated Fri Jun 09 11:46:43 CST 2017
     */
    public Integer getUnbindTime() {
        return unbindTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column site_weixin.unbind_time
     *
     * @param unbindTime the value for site_weixin.unbind_time
     *
     * @mbggenerated Fri Jun 09 11:46:43 CST 2017
     */
    public void setUnbindTime(Integer unbindTime) {
        this.unbindTime = unbindTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column site_weixin.is_del
     *
     * @return the value of site_weixin.is_del
     *
     * @mbggenerated Fri Jun 09 11:46:43 CST 2017
     */
    public Integer getIsDel() {
        return isDel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column site_weixin.is_del
     *
     * @param isDel the value for site_weixin.is_del
     *
     * @mbggenerated Fri Jun 09 11:46:43 CST 2017
     */
    public void setIsDel(Integer isDel) {
        this.isDel = isDel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column site_weixin.create_time
     *
     * @return the value of site_weixin.create_time
     *
     * @mbggenerated Fri Jun 09 11:46:43 CST 2017
     */
    public Integer getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column site_weixin.create_time
     *
     * @param createTime the value for site_weixin.create_time
     *
     * @mbggenerated Fri Jun 09 11:46:43 CST 2017
     */
    public void setCreateTime(Integer createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column site_weixin.update_time
     *
     * @return the value of site_weixin.update_time
     *
     * @mbggenerated Fri Jun 09 11:46:43 CST 2017
     */
    public Integer getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column site_weixin.update_time
     *
     * @param updateTime the value for site_weixin.update_time
     *
     * @mbggenerated Fri Jun 09 11:46:43 CST 2017
     */
    public void setUpdateTime(Integer updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column site_weixin.user_id
     *
     * @return the value of site_weixin.user_id
     *
     * @mbggenerated Fri Jun 09 11:46:43 CST 2017
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column site_weixin.user_id
     *
     * @param userId the value for site_weixin.user_id
     *
     * @mbggenerated Fri Jun 09 11:46:43 CST 2017
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column site_weixin.menu_json
     *
     * @return the value of site_weixin.menu_json
     *
     * @mbggenerated Fri Jun 09 11:46:43 CST 2017
     */
    public String getMenuJson() {
        return menuJson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column site_weixin.menu_json
     *
     * @param menuJson the value for site_weixin.menu_json
     *
     * @mbggenerated Fri Jun 09 11:46:43 CST 2017
     */
    public void setMenuJson(String menuJson) {
        this.menuJson = menuJson;
    }
}