package com.kuaizhan.kzweixin.pojo.po.auto;

public class WeixinMenuItem {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weixin_menu_item.menu_key
     *
     * @mbggenerated Thu May 25 17:18:21 CST 2017
     */
    private Long menuKey;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weixin_menu_item.weixin_appid
     *
     * @mbggenerated Thu May 25 17:18:21 CST 2017
     */
    private Long weixinAppid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weixin_menu_item.response_type
     *
     * @mbggenerated Thu May 25 17:18:21 CST 2017
     */
    private Integer responseType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weixin_menu_item.status
     *
     * @mbggenerated Thu May 25 17:18:21 CST 2017
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weixin_menu_item.create_time
     *
     * @mbggenerated Thu May 25 17:18:21 CST 2017
     */
    private Integer createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weixin_menu_item.update_time
     *
     * @mbggenerated Thu May 25 17:18:21 CST 2017
     */
    private Integer updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weixin_menu_item.response_json
     *
     * @mbggenerated Thu May 25 17:18:21 CST 2017
     */
    private String responseJson;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column weixin_menu_item.menu_key
     *
     * @return the value of weixin_menu_item.menu_key
     *
     * @mbggenerated Thu May 25 17:18:21 CST 2017
     */
    public Long getMenuKey() {
        return menuKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column weixin_menu_item.menu_key
     *
     * @param menuKey the value for weixin_menu_item.menu_key
     *
     * @mbggenerated Thu May 25 17:18:21 CST 2017
     */
    public void setMenuKey(Long menuKey) {
        this.menuKey = menuKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column weixin_menu_item.weixin_appid
     *
     * @return the value of weixin_menu_item.weixin_appid
     *
     * @mbggenerated Thu May 25 17:18:21 CST 2017
     */
    public Long getWeixinAppid() {
        return weixinAppid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column weixin_menu_item.weixin_appid
     *
     * @param weixinAppid the value for weixin_menu_item.weixin_appid
     *
     * @mbggenerated Thu May 25 17:18:21 CST 2017
     */
    public void setWeixinAppid(Long weixinAppid) {
        this.weixinAppid = weixinAppid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column weixin_menu_item.response_type
     *
     * @return the value of weixin_menu_item.response_type
     *
     * @mbggenerated Thu May 25 17:18:21 CST 2017
     */
    public Integer getResponseType() {
        return responseType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column weixin_menu_item.response_type
     *
     * @param responseType the value for weixin_menu_item.response_type
     *
     * @mbggenerated Thu May 25 17:18:21 CST 2017
     */
    public void setResponseType(Integer responseType) {
        this.responseType = responseType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column weixin_menu_item.status
     *
     * @return the value of weixin_menu_item.status
     *
     * @mbggenerated Thu May 25 17:18:21 CST 2017
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column weixin_menu_item.status
     *
     * @param status the value for weixin_menu_item.status
     *
     * @mbggenerated Thu May 25 17:18:21 CST 2017
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column weixin_menu_item.create_time
     *
     * @return the value of weixin_menu_item.create_time
     *
     * @mbggenerated Thu May 25 17:18:21 CST 2017
     */
    public Integer getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column weixin_menu_item.create_time
     *
     * @param createTime the value for weixin_menu_item.create_time
     *
     * @mbggenerated Thu May 25 17:18:21 CST 2017
     */
    public void setCreateTime(Integer createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column weixin_menu_item.update_time
     *
     * @return the value of weixin_menu_item.update_time
     *
     * @mbggenerated Thu May 25 17:18:21 CST 2017
     */
    public Integer getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column weixin_menu_item.update_time
     *
     * @param updateTime the value for weixin_menu_item.update_time
     *
     * @mbggenerated Thu May 25 17:18:21 CST 2017
     */
    public void setUpdateTime(Integer updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column weixin_menu_item.response_json
     *
     * @return the value of weixin_menu_item.response_json
     *
     * @mbggenerated Thu May 25 17:18:21 CST 2017
     */
    public String getResponseJson() {
        return responseJson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column weixin_menu_item.response_json
     *
     * @param responseJson the value for weixin_menu_item.response_json
     *
     * @mbggenerated Thu May 25 17:18:21 CST 2017
     */
    public void setResponseJson(String responseJson) {
        this.responseJson = responseJson;
    }
}