package com.kuaizhan.kzweixin.pojo.po.auto;

public class WeixinMsgConfig {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weixin_msg_config.weixin_appid
     *
     * @mbggenerated Tue May 16 17:13:45 CST 2017
     */
    private Long weixinAppid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weixin_msg_config.last_read_time
     *
     * @mbggenerated Tue May 16 17:13:45 CST 2017
     */
    private Integer lastReadTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weixin_msg_config.create_time
     *
     * @mbggenerated Tue May 16 17:13:45 CST 2017
     */
    private Integer createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weixin_msg_config.update_time
     *
     * @mbggenerated Tue May 16 17:13:45 CST 2017
     */
    private Integer updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weixin_msg_config.quick_reply_json
     *
     * @mbggenerated Tue May 16 17:13:45 CST 2017
     */
    private String quickReplyJson;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column weixin_msg_config.weixin_appid
     *
     * @return the value of weixin_msg_config.weixin_appid
     *
     * @mbggenerated Tue May 16 17:13:45 CST 2017
     */
    public Long getWeixinAppid() {
        return weixinAppid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column weixin_msg_config.weixin_appid
     *
     * @param weixinAppid the value for weixin_msg_config.weixin_appid
     *
     * @mbggenerated Tue May 16 17:13:45 CST 2017
     */
    public void setWeixinAppid(Long weixinAppid) {
        this.weixinAppid = weixinAppid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column weixin_msg_config.last_read_time
     *
     * @return the value of weixin_msg_config.last_read_time
     *
     * @mbggenerated Tue May 16 17:13:45 CST 2017
     */
    public Integer getLastReadTime() {
        return lastReadTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column weixin_msg_config.last_read_time
     *
     * @param lastReadTime the value for weixin_msg_config.last_read_time
     *
     * @mbggenerated Tue May 16 17:13:45 CST 2017
     */
    public void setLastReadTime(Integer lastReadTime) {
        this.lastReadTime = lastReadTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column weixin_msg_config.create_time
     *
     * @return the value of weixin_msg_config.create_time
     *
     * @mbggenerated Tue May 16 17:13:45 CST 2017
     */
    public Integer getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column weixin_msg_config.create_time
     *
     * @param createTime the value for weixin_msg_config.create_time
     *
     * @mbggenerated Tue May 16 17:13:45 CST 2017
     */
    public void setCreateTime(Integer createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column weixin_msg_config.update_time
     *
     * @return the value of weixin_msg_config.update_time
     *
     * @mbggenerated Tue May 16 17:13:45 CST 2017
     */
    public Integer getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column weixin_msg_config.update_time
     *
     * @param updateTime the value for weixin_msg_config.update_time
     *
     * @mbggenerated Tue May 16 17:13:45 CST 2017
     */
    public void setUpdateTime(Integer updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column weixin_msg_config.quick_reply_json
     *
     * @return the value of weixin_msg_config.quick_reply_json
     *
     * @mbggenerated Tue May 16 17:13:45 CST 2017
     */
    public String getQuickReplyJson() {
        return quickReplyJson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column weixin_msg_config.quick_reply_json
     *
     * @param quickReplyJson the value for weixin_msg_config.quick_reply_json
     *
     * @mbggenerated Tue May 16 17:13:45 CST 2017
     */
    public void setQuickReplyJson(String quickReplyJson) {
        this.quickReplyJson = quickReplyJson;
    }
}