package com.kuaizhan.kzweixin.dao.po.auto;

public class ConditionMenuPO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weixin_conditional_menu.id
     *
     * @mbg.generated Tue Jun 13 19:43:12 CST 2017
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weixin_conditional_menu.weixin_appid
     *
     * @mbg.generated Tue Jun 13 19:43:12 CST 2017
     */
    private Long weixinAppid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weixin_conditional_menu.menu_name
     *
     * @mbg.generated Tue Jun 13 19:43:12 CST 2017
     */
    private String menuName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weixin_conditional_menu.menu_id
     *
     * @mbg.generated Tue Jun 13 19:43:12 CST 2017
     */
    private String menuId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weixin_conditional_menu.status
     *
     * @mbg.generated Tue Jun 13 19:43:12 CST 2017
     */
    private Integer status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weixin_conditional_menu.create_time
     *
     * @mbg.generated Tue Jun 13 19:43:12 CST 2017
     */
    private Integer createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weixin_conditional_menu.update_time
     *
     * @mbg.generated Tue Jun 13 19:43:12 CST 2017
     */
    private Integer updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weixin_conditional_menu.menu_json
     *
     * @mbg.generated Tue Jun 13 19:43:12 CST 2017
     */
    private String menuJson;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column weixin_conditional_menu.id
     *
     * @return the value of weixin_conditional_menu.id
     *
     * @mbg.generated Tue Jun 13 19:43:12 CST 2017
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column weixin_conditional_menu.id
     *
     * @param id the value for weixin_conditional_menu.id
     *
     * @mbg.generated Tue Jun 13 19:43:12 CST 2017
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column weixin_conditional_menu.weixin_appid
     *
     * @return the value of weixin_conditional_menu.weixin_appid
     *
     * @mbg.generated Tue Jun 13 19:43:12 CST 2017
     */
    public Long getWeixinAppid() {
        return weixinAppid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column weixin_conditional_menu.weixin_appid
     *
     * @param weixinAppid the value for weixin_conditional_menu.weixin_appid
     *
     * @mbg.generated Tue Jun 13 19:43:12 CST 2017
     */
    public void setWeixinAppid(Long weixinAppid) {
        this.weixinAppid = weixinAppid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column weixin_conditional_menu.menu_name
     *
     * @return the value of weixin_conditional_menu.menu_name
     *
     * @mbg.generated Tue Jun 13 19:43:12 CST 2017
     */
    public String getMenuName() {
        return menuName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column weixin_conditional_menu.menu_name
     *
     * @param menuName the value for weixin_conditional_menu.menu_name
     *
     * @mbg.generated Tue Jun 13 19:43:12 CST 2017
     */
    public void setMenuName(String menuName) {
        this.menuName = menuName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column weixin_conditional_menu.menu_id
     *
     * @return the value of weixin_conditional_menu.menu_id
     *
     * @mbg.generated Tue Jun 13 19:43:12 CST 2017
     */
    public String getMenuId() {
        return menuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column weixin_conditional_menu.menu_id
     *
     * @param menuId the value for weixin_conditional_menu.menu_id
     *
     * @mbg.generated Tue Jun 13 19:43:12 CST 2017
     */
    public void setMenuId(String menuId) {
        this.menuId = menuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column weixin_conditional_menu.status
     *
     * @return the value of weixin_conditional_menu.status
     *
     * @mbg.generated Tue Jun 13 19:43:12 CST 2017
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column weixin_conditional_menu.status
     *
     * @param status the value for weixin_conditional_menu.status
     *
     * @mbg.generated Tue Jun 13 19:43:12 CST 2017
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column weixin_conditional_menu.create_time
     *
     * @return the value of weixin_conditional_menu.create_time
     *
     * @mbg.generated Tue Jun 13 19:43:12 CST 2017
     */
    public Integer getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column weixin_conditional_menu.create_time
     *
     * @param createTime the value for weixin_conditional_menu.create_time
     *
     * @mbg.generated Tue Jun 13 19:43:12 CST 2017
     */
    public void setCreateTime(Integer createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column weixin_conditional_menu.update_time
     *
     * @return the value of weixin_conditional_menu.update_time
     *
     * @mbg.generated Tue Jun 13 19:43:12 CST 2017
     */
    public Integer getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column weixin_conditional_menu.update_time
     *
     * @param updateTime the value for weixin_conditional_menu.update_time
     *
     * @mbg.generated Tue Jun 13 19:43:12 CST 2017
     */
    public void setUpdateTime(Integer updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column weixin_conditional_menu.menu_json
     *
     * @return the value of weixin_conditional_menu.menu_json
     *
     * @mbg.generated Tue Jun 13 19:43:12 CST 2017
     */
    public String getMenuJson() {
        return menuJson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column weixin_conditional_menu.menu_json
     *
     * @param menuJson the value for weixin_conditional_menu.menu_json
     *
     * @mbg.generated Tue Jun 13 19:43:12 CST 2017
     */
    public void setMenuJson(String menuJson) {
        this.menuJson = menuJson;
    }
}