package com.kuaizhan.kzweixin.dao.po.auto;

public class FanPO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weixin_fans_0.fan_id
     *
     * @mbg.generated Fri Jun 16 19:23:55 CST 2017
     */
    private Integer fanId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weixin_fans_0.app_id
     *
     * @mbg.generated Fri Jun 16 19:23:55 CST 2017
     */
    private String appId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weixin_fans_0.open_id
     *
     * @mbg.generated Fri Jun 16 19:23:55 CST 2017
     */
    private String openId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weixin_fans_0.nick_name
     *
     * @mbg.generated Fri Jun 16 19:23:55 CST 2017
     */
    private String nickName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weixin_fans_0.sex
     *
     * @mbg.generated Fri Jun 16 19:23:55 CST 2017
     */
    private Integer sex;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weixin_fans_0.city
     *
     * @mbg.generated Fri Jun 16 19:23:55 CST 2017
     */
    private String city;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weixin_fans_0.country
     *
     * @mbg.generated Fri Jun 16 19:23:55 CST 2017
     */
    private String country;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weixin_fans_0.province
     *
     * @mbg.generated Fri Jun 16 19:23:55 CST 2017
     */
    private String province;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weixin_fans_0.language
     *
     * @mbg.generated Fri Jun 16 19:23:55 CST 2017
     */
    private String language;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weixin_fans_0.head_img_url
     *
     * @mbg.generated Fri Jun 16 19:23:55 CST 2017
     */
    private String headImgUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weixin_fans_0.subscribe_time
     *
     * @mbg.generated Fri Jun 16 19:23:55 CST 2017
     */
    private Integer subscribeTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weixin_fans_0.union_id
     *
     * @mbg.generated Fri Jun 16 19:23:55 CST 2017
     */
    private String unionId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weixin_fans_0.remark
     *
     * @mbg.generated Fri Jun 16 19:23:55 CST 2017
     */
    private String remark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weixin_fans_0.group_id
     *
     * @mbg.generated Fri Jun 16 19:23:55 CST 2017
     */
    private Integer groupId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weixin_fans_0.tag_ids_json
     *
     * @mbg.generated Fri Jun 16 19:23:55 CST 2017
     */
    private String tagIdsJson;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weixin_fans_0.in_blacklist
     *
     * @mbg.generated Fri Jun 16 19:23:55 CST 2017
     */
    private Integer inBlacklist;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weixin_fans_0.last_interact_time
     *
     * @mbg.generated Fri Jun 16 19:23:55 CST 2017
     */
    private Integer lastInteractTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weixin_fans_0.status
     *
     * @mbg.generated Fri Jun 16 19:23:55 CST 2017
     */
    private Integer status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weixin_fans_0.create_time
     *
     * @mbg.generated Fri Jun 16 19:23:55 CST 2017
     */
    private Integer createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weixin_fans_0.update_time
     *
     * @mbg.generated Fri Jun 16 19:23:55 CST 2017
     */
    private Integer updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column weixin_fans_0.fan_id
     *
     * @return the value of weixin_fans_0.fan_id
     *
     * @mbg.generated Fri Jun 16 19:23:55 CST 2017
     */
    public Integer getFanId() {
        return fanId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column weixin_fans_0.fan_id
     *
     * @param fanId the value for weixin_fans_0.fan_id
     *
     * @mbg.generated Fri Jun 16 19:23:55 CST 2017
     */
    public void setFanId(Integer fanId) {
        this.fanId = fanId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column weixin_fans_0.app_id
     *
     * @return the value of weixin_fans_0.app_id
     *
     * @mbg.generated Fri Jun 16 19:23:55 CST 2017
     */
    public String getAppId() {
        return appId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column weixin_fans_0.app_id
     *
     * @param appId the value for weixin_fans_0.app_id
     *
     * @mbg.generated Fri Jun 16 19:23:55 CST 2017
     */
    public void setAppId(String appId) {
        this.appId = appId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column weixin_fans_0.open_id
     *
     * @return the value of weixin_fans_0.open_id
     *
     * @mbg.generated Fri Jun 16 19:23:55 CST 2017
     */
    public String getOpenId() {
        return openId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column weixin_fans_0.open_id
     *
     * @param openId the value for weixin_fans_0.open_id
     *
     * @mbg.generated Fri Jun 16 19:23:55 CST 2017
     */
    public void setOpenId(String openId) {
        this.openId = openId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column weixin_fans_0.nick_name
     *
     * @return the value of weixin_fans_0.nick_name
     *
     * @mbg.generated Fri Jun 16 19:23:55 CST 2017
     */
    public String getNickName() {
        return nickName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column weixin_fans_0.nick_name
     *
     * @param nickName the value for weixin_fans_0.nick_name
     *
     * @mbg.generated Fri Jun 16 19:23:55 CST 2017
     */
    public void setNickName(String nickName) {
        this.nickName = nickName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column weixin_fans_0.sex
     *
     * @return the value of weixin_fans_0.sex
     *
     * @mbg.generated Fri Jun 16 19:23:55 CST 2017
     */
    public Integer getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column weixin_fans_0.sex
     *
     * @param sex the value for weixin_fans_0.sex
     *
     * @mbg.generated Fri Jun 16 19:23:55 CST 2017
     */
    public void setSex(Integer sex) {
        this.sex = sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column weixin_fans_0.city
     *
     * @return the value of weixin_fans_0.city
     *
     * @mbg.generated Fri Jun 16 19:23:55 CST 2017
     */
    public String getCity() {
        return city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column weixin_fans_0.city
     *
     * @param city the value for weixin_fans_0.city
     *
     * @mbg.generated Fri Jun 16 19:23:55 CST 2017
     */
    public void setCity(String city) {
        this.city = city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column weixin_fans_0.country
     *
     * @return the value of weixin_fans_0.country
     *
     * @mbg.generated Fri Jun 16 19:23:55 CST 2017
     */
    public String getCountry() {
        return country;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column weixin_fans_0.country
     *
     * @param country the value for weixin_fans_0.country
     *
     * @mbg.generated Fri Jun 16 19:23:55 CST 2017
     */
    public void setCountry(String country) {
        this.country = country;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column weixin_fans_0.province
     *
     * @return the value of weixin_fans_0.province
     *
     * @mbg.generated Fri Jun 16 19:23:55 CST 2017
     */
    public String getProvince() {
        return province;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column weixin_fans_0.province
     *
     * @param province the value for weixin_fans_0.province
     *
     * @mbg.generated Fri Jun 16 19:23:55 CST 2017
     */
    public void setProvince(String province) {
        this.province = province;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column weixin_fans_0.language
     *
     * @return the value of weixin_fans_0.language
     *
     * @mbg.generated Fri Jun 16 19:23:55 CST 2017
     */
    public String getLanguage() {
        return language;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column weixin_fans_0.language
     *
     * @param language the value for weixin_fans_0.language
     *
     * @mbg.generated Fri Jun 16 19:23:55 CST 2017
     */
    public void setLanguage(String language) {
        this.language = language;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column weixin_fans_0.head_img_url
     *
     * @return the value of weixin_fans_0.head_img_url
     *
     * @mbg.generated Fri Jun 16 19:23:55 CST 2017
     */
    public String getHeadImgUrl() {
        return headImgUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column weixin_fans_0.head_img_url
     *
     * @param headImgUrl the value for weixin_fans_0.head_img_url
     *
     * @mbg.generated Fri Jun 16 19:23:55 CST 2017
     */
    public void setHeadImgUrl(String headImgUrl) {
        this.headImgUrl = headImgUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column weixin_fans_0.subscribe_time
     *
     * @return the value of weixin_fans_0.subscribe_time
     *
     * @mbg.generated Fri Jun 16 19:23:55 CST 2017
     */
    public Integer getSubscribeTime() {
        return subscribeTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column weixin_fans_0.subscribe_time
     *
     * @param subscribeTime the value for weixin_fans_0.subscribe_time
     *
     * @mbg.generated Fri Jun 16 19:23:55 CST 2017
     */
    public void setSubscribeTime(Integer subscribeTime) {
        this.subscribeTime = subscribeTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column weixin_fans_0.union_id
     *
     * @return the value of weixin_fans_0.union_id
     *
     * @mbg.generated Fri Jun 16 19:23:55 CST 2017
     */
    public String getUnionId() {
        return unionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column weixin_fans_0.union_id
     *
     * @param unionId the value for weixin_fans_0.union_id
     *
     * @mbg.generated Fri Jun 16 19:23:55 CST 2017
     */
    public void setUnionId(String unionId) {
        this.unionId = unionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column weixin_fans_0.remark
     *
     * @return the value of weixin_fans_0.remark
     *
     * @mbg.generated Fri Jun 16 19:23:55 CST 2017
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column weixin_fans_0.remark
     *
     * @param remark the value for weixin_fans_0.remark
     *
     * @mbg.generated Fri Jun 16 19:23:55 CST 2017
     */
    public void setRemark(String remark) {
        this.remark = remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column weixin_fans_0.group_id
     *
     * @return the value of weixin_fans_0.group_id
     *
     * @mbg.generated Fri Jun 16 19:23:55 CST 2017
     */
    public Integer getGroupId() {
        return groupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column weixin_fans_0.group_id
     *
     * @param groupId the value for weixin_fans_0.group_id
     *
     * @mbg.generated Fri Jun 16 19:23:55 CST 2017
     */
    public void setGroupId(Integer groupId) {
        this.groupId = groupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column weixin_fans_0.tag_ids_json
     *
     * @return the value of weixin_fans_0.tag_ids_json
     *
     * @mbg.generated Fri Jun 16 19:23:55 CST 2017
     */
    public String getTagIdsJson() {
        return tagIdsJson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column weixin_fans_0.tag_ids_json
     *
     * @param tagIdsJson the value for weixin_fans_0.tag_ids_json
     *
     * @mbg.generated Fri Jun 16 19:23:55 CST 2017
     */
    public void setTagIdsJson(String tagIdsJson) {
        this.tagIdsJson = tagIdsJson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column weixin_fans_0.in_blacklist
     *
     * @return the value of weixin_fans_0.in_blacklist
     *
     * @mbg.generated Fri Jun 16 19:23:55 CST 2017
     */
    public Integer getInBlacklist() {
        return inBlacklist;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column weixin_fans_0.in_blacklist
     *
     * @param inBlacklist the value for weixin_fans_0.in_blacklist
     *
     * @mbg.generated Fri Jun 16 19:23:55 CST 2017
     */
    public void setInBlacklist(Integer inBlacklist) {
        this.inBlacklist = inBlacklist;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column weixin_fans_0.last_interact_time
     *
     * @return the value of weixin_fans_0.last_interact_time
     *
     * @mbg.generated Fri Jun 16 19:23:55 CST 2017
     */
    public Integer getLastInteractTime() {
        return lastInteractTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column weixin_fans_0.last_interact_time
     *
     * @param lastInteractTime the value for weixin_fans_0.last_interact_time
     *
     * @mbg.generated Fri Jun 16 19:23:55 CST 2017
     */
    public void setLastInteractTime(Integer lastInteractTime) {
        this.lastInteractTime = lastInteractTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column weixin_fans_0.status
     *
     * @return the value of weixin_fans_0.status
     *
     * @mbg.generated Fri Jun 16 19:23:55 CST 2017
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column weixin_fans_0.status
     *
     * @param status the value for weixin_fans_0.status
     *
     * @mbg.generated Fri Jun 16 19:23:55 CST 2017
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column weixin_fans_0.create_time
     *
     * @return the value of weixin_fans_0.create_time
     *
     * @mbg.generated Fri Jun 16 19:23:55 CST 2017
     */
    public Integer getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column weixin_fans_0.create_time
     *
     * @param createTime the value for weixin_fans_0.create_time
     *
     * @mbg.generated Fri Jun 16 19:23:55 CST 2017
     */
    public void setCreateTime(Integer createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column weixin_fans_0.update_time
     *
     * @return the value of weixin_fans_0.update_time
     *
     * @mbg.generated Fri Jun 16 19:23:55 CST 2017
     */
    public Integer getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column weixin_fans_0.update_time
     *
     * @param updateTime the value for weixin_fans_0.update_time
     *
     * @mbg.generated Fri Jun 16 19:23:55 CST 2017
     */
    public void setUpdateTime(Integer updateTime) {
        this.updateTime = updateTime;
    }
}