package com.kuaizhan.kzweixin.dao.po.auto;

public class OpenIdPO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weixin_open_ids_0.id
     *
     * @mbg.generated Wed Jun 14 10:44:57 CST 2017
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weixin_open_ids_0.app_id
     *
     * @mbg.generated Wed Jun 14 10:44:57 CST 2017
     */
    private String appId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weixin_open_ids_0.open_id
     *
     * @mbg.generated Wed Jun 14 10:44:57 CST 2017
     */
    private String openId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weixin_open_ids_0.status
     *
     * @mbg.generated Wed Jun 14 10:44:57 CST 2017
     */
    private Boolean status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weixin_open_ids_0.create_time
     *
     * @mbg.generated Wed Jun 14 10:44:57 CST 2017
     */
    private Integer createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weixin_open_ids_0.update_time
     *
     * @mbg.generated Wed Jun 14 10:44:57 CST 2017
     */
    private Integer updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column weixin_open_ids_0.id
     *
     * @return the value of weixin_open_ids_0.id
     *
     * @mbg.generated Wed Jun 14 10:44:57 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column weixin_open_ids_0.id
     *
     * @param id the value for weixin_open_ids_0.id
     *
     * @mbg.generated Wed Jun 14 10:44:57 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column weixin_open_ids_0.app_id
     *
     * @return the value of weixin_open_ids_0.app_id
     *
     * @mbg.generated Wed Jun 14 10:44:57 CST 2017
     */
    public String getAppId() {
        return appId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column weixin_open_ids_0.app_id
     *
     * @param appId the value for weixin_open_ids_0.app_id
     *
     * @mbg.generated Wed Jun 14 10:44:57 CST 2017
     */
    public void setAppId(String appId) {
        this.appId = appId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column weixin_open_ids_0.open_id
     *
     * @return the value of weixin_open_ids_0.open_id
     *
     * @mbg.generated Wed Jun 14 10:44:57 CST 2017
     */
    public String getOpenId() {
        return openId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column weixin_open_ids_0.open_id
     *
     * @param openId the value for weixin_open_ids_0.open_id
     *
     * @mbg.generated Wed Jun 14 10:44:57 CST 2017
     */
    public void setOpenId(String openId) {
        this.openId = openId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column weixin_open_ids_0.status
     *
     * @return the value of weixin_open_ids_0.status
     *
     * @mbg.generated Wed Jun 14 10:44:57 CST 2017
     */
    public Boolean getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column weixin_open_ids_0.status
     *
     * @param status the value for weixin_open_ids_0.status
     *
     * @mbg.generated Wed Jun 14 10:44:57 CST 2017
     */
    public void setStatus(Boolean status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column weixin_open_ids_0.create_time
     *
     * @return the value of weixin_open_ids_0.create_time
     *
     * @mbg.generated Wed Jun 14 10:44:57 CST 2017
     */
    public Integer getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column weixin_open_ids_0.create_time
     *
     * @param createTime the value for weixin_open_ids_0.create_time
     *
     * @mbg.generated Wed Jun 14 10:44:57 CST 2017
     */
    public void setCreateTime(Integer createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column weixin_open_ids_0.update_time
     *
     * @return the value of weixin_open_ids_0.update_time
     *
     * @mbg.generated Wed Jun 14 10:44:57 CST 2017
     */
    public Integer getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column weixin_open_ids_0.update_time
     *
     * @param updateTime the value for weixin_open_ids_0.update_time
     *
     * @mbg.generated Wed Jun 14 10:44:57 CST 2017
     */
    public void setUpdateTime(Integer updateTime) {
        this.updateTime = updateTime;
    }
}