package com.kuaizhan.kzweixin.dao.mapper.auto;

import com.kuaizhan.kzweixin.dao.po.auto.AccountPO;
import com.kuaizhan.kzweixin.dao.po.auto.AccountPOExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface AccountMapper {
    long countByExample(AccountPOExample example);

    int deleteByExample(AccountPOExample example);

    int deleteByPrimaryKey(Long weixinAppid);

    int insert(AccountPO record);

    int insertSelective(AccountPO record);

    List<AccountPO> selectByExampleWithBLOBsWithRowbounds(AccountPOExample example, RowBounds rowBounds);

    List<AccountPO> selectByExampleWithBLOBs(AccountPOExample example);

    List<AccountPO> selectByExampleWithRowbounds(AccountPOExample example, RowBounds rowBounds);

    List<AccountPO> selectByExample(AccountPOExample example);

    AccountPO selectByPrimaryKey(Long weixinAppid);

    int updateByExampleSelective(@Param("record") AccountPO record, @Param("example") AccountPOExample example);

    int updateByExampleWithBLOBs(@Param("record") AccountPO record, @Param("example") AccountPOExample example);

    int updateByExample(@Param("record") AccountPO record, @Param("example") AccountPOExample example);

    int updateByPrimaryKeySelective(AccountPO record);

    int updateByPrimaryKeyWithBLOBs(AccountPO record);

    int updateByPrimaryKey(AccountPO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table site_weixin
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int upsert(AccountPO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table site_weixin
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int upsertSelective(AccountPO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table site_weixin
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int upsertWithBLOBs(AccountPO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table site_weixin
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int upsertSelectiveWithBLOBs(AccountPO record);
}