package com.kuaizhan.kzweixin.dao.mapper.auto;

import com.kuaizhan.kzweixin.dao.po.auto.AccountPO;
import com.kuaizhan.kzweixin.dao.po.auto.AccountPOExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface AccountMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table site_weixin
     *
     * @mbg.generated
     */
    long countByExample(AccountPOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table site_weixin
     *
     * @mbg.generated
     */
    int deleteByExample(AccountPOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table site_weixin
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long weixinAppid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table site_weixin
     *
     * @mbg.generated
     */
    int insert(AccountPO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table site_weixin
     *
     * @mbg.generated
     */
    int insertSelective(AccountPO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table site_weixin
     *
     * @mbg.generated
     */
    List<AccountPO> selectByExampleWithBLOBs(AccountPOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table site_weixin
     *
     * @mbg.generated
     */
    List<AccountPO> selectByExample(AccountPOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table site_weixin
     *
     * @mbg.generated
     */
    AccountPO selectByPrimaryKey(Long weixinAppid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table site_weixin
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") AccountPO record, @Param("example") AccountPOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table site_weixin
     *
     * @mbg.generated
     */
    int updateByExampleWithBLOBs(@Param("record") AccountPO record, @Param("example") AccountPOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table site_weixin
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") AccountPO record, @Param("example") AccountPOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table site_weixin
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(AccountPO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table site_weixin
     *
     * @mbg.generated
     */
    int updateByPrimaryKeyWithBLOBs(AccountPO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table site_weixin
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(AccountPO record);
}