package com.kuaizhan.kzweixin.dao.mapper.auto;

import com.kuaizhan.kzweixin.dao.po.auto.ConditionMenuPO;
import com.kuaizhan.kzweixin.dao.po.auto.ConditionMenuPOExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ConditionMenuMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weixin_conditional_menu
     *
     * @mbg.generated Tue Jun 13 19:43:12 CST 2017
     */
    long countByExample(ConditionMenuPOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weixin_conditional_menu
     *
     * @mbg.generated Tue Jun 13 19:43:12 CST 2017
     */
    int deleteByExample(ConditionMenuPOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weixin_conditional_menu
     *
     * @mbg.generated Tue Jun 13 19:43:12 CST 2017
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weixin_conditional_menu
     *
     * @mbg.generated Tue Jun 13 19:43:12 CST 2017
     */
    int insert(ConditionMenuPO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weixin_conditional_menu
     *
     * @mbg.generated Tue Jun 13 19:43:12 CST 2017
     */
    int insertSelective(ConditionMenuPO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weixin_conditional_menu
     *
     * @mbg.generated Tue Jun 13 19:43:12 CST 2017
     */
    List<ConditionMenuPO> selectByExampleWithBLOBs(ConditionMenuPOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weixin_conditional_menu
     *
     * @mbg.generated Tue Jun 13 19:43:12 CST 2017
     */
    List<ConditionMenuPO> selectByExample(ConditionMenuPOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weixin_conditional_menu
     *
     * @mbg.generated Tue Jun 13 19:43:12 CST 2017
     */
    ConditionMenuPO selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weixin_conditional_menu
     *
     * @mbg.generated Tue Jun 13 19:43:12 CST 2017
     */
    int updateByExampleSelective(@Param("record") ConditionMenuPO record, @Param("example") ConditionMenuPOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weixin_conditional_menu
     *
     * @mbg.generated Tue Jun 13 19:43:12 CST 2017
     */
    int updateByExampleWithBLOBs(@Param("record") ConditionMenuPO record, @Param("example") ConditionMenuPOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weixin_conditional_menu
     *
     * @mbg.generated Tue Jun 13 19:43:12 CST 2017
     */
    int updateByExample(@Param("record") ConditionMenuPO record, @Param("example") ConditionMenuPOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weixin_conditional_menu
     *
     * @mbg.generated Tue Jun 13 19:43:12 CST 2017
     */
    int updateByPrimaryKeySelective(ConditionMenuPO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weixin_conditional_menu
     *
     * @mbg.generated Tue Jun 13 19:43:12 CST 2017
     */
    int updateByPrimaryKeyWithBLOBs(ConditionMenuPO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weixin_conditional_menu
     *
     * @mbg.generated Tue Jun 13 19:43:12 CST 2017
     */
    int updateByPrimaryKey(ConditionMenuPO record);
}