package com.kuaizhan.kzweixin.dao.mapper.auto;

import com.kuaizhan.kzweixin.dao.po.auto.FanPO;
import com.kuaizhan.kzweixin.dao.po.auto.FanPOExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface FanMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weixin_fans_0
     *
     * @mbg.generated Fri Jun 16 19:23:55 CST 2017
     */
    long countByExample(@Param("example") FanPOExample example, @Param("tableName") String tableName);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weixin_fans_0
     *
     * @mbg.generated Fri Jun 16 19:23:55 CST 2017
     */
    int deleteByExample(@Param("example") FanPOExample example, @Param("tableName") String tableName);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weixin_fans_0
     *
     * @mbg.generated Fri Jun 16 19:23:55 CST 2017
     */
    int deleteByPrimaryKey(@Param("fanId") Integer fanId, @Param("tableName") String tableName);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weixin_fans_0
     *
     * @mbg.generated Fri Jun 16 19:23:55 CST 2017
     */
    int insert(@Param("record") FanPO record, @Param("tableName") String tableName);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weixin_fans_0
     *
     * @mbg.generated Fri Jun 16 19:23:55 CST 2017
     */
    int insertSelective(@Param("record") FanPO record, @Param("tableName") String tableName);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weixin_fans_0
     *
     * @mbg.generated
     */
    List<FanPO> selectByExampleWithRowbounds(@Param("example") FanPOExample example, @Param("rowBounds") RowBounds rowBounds, @Param("tableName") String tableName);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weixin_fans_0
     *
     * @mbg.generated Fri Jun 16 19:23:55 CST 2017
     */
    List<FanPO> selectByExample(@Param("example") FanPOExample example, @Param("tableName") String tableName);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weixin_fans_0
     *
     * @mbg.generated Fri Jun 16 19:23:55 CST 2017
     */
    FanPO selectByPrimaryKey(@Param("fanId") Integer fanId, @Param("tableName") String tableName);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weixin_fans_0
     *
     * @mbg.generated Fri Jun 16 19:23:55 CST 2017
     */
    int updateByExampleSelective(@Param("record") FanPO record, @Param("example") FanPOExample example, @Param("tableName") String tableName);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weixin_fans_0
     *
     * @mbg.generated Fri Jun 16 19:23:55 CST 2017
     */
    int updateByExample(@Param("record") FanPO record, @Param("example") FanPOExample example, @Param("tableName") String tableName);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weixin_fans_0
     *
     * @mbg.generated Fri Jun 16 19:23:55 CST 2017
     */
    int updateByPrimaryKeySelective(@Param("record") FanPO record, @Param("tableName") String tableName);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weixin_fans_0
     *
     * @mbg.generated Fri Jun 16 19:23:55 CST 2017
     */
    int updateByPrimaryKey(@Param("record") FanPO record, @Param("tableName") String tableName);
}