package com.kuaizhan.kzweixin.dao.mapper.auto;

import com.kuaizhan.kzweixin.dao.po.auto.FanPO;
import com.kuaizhan.kzweixin.dao.po.auto.FanPOExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface FanMapper {
    long countByExample(FanPOExample example);

    int deleteByExample(FanPOExample example);

    int deleteByPrimaryKey(Integer fanId);

    int insert(FanPO record);

    int insertSelective(FanPO record);

    List<FanPO> selectByExampleWithRowbounds(FanPOExample example, RowBounds rowBounds);

    List<FanPO> selectByExample(FanPOExample example);

    FanPO selectByPrimaryKey(Integer fanId);

    int updateByExampleSelective(@Param("record") FanPO record, @Param("example") FanPOExample example);

    int updateByExample(@Param("record") FanPO record, @Param("example") FanPOExample example);

    int updateByPrimaryKeySelective(FanPO record);

    int updateByPrimaryKey(FanPO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weixin_fans_0
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int upsert(FanPO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weixin_fans_0
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int upsertSelective(FanPO record);
}