package com.kuaizhan.kzweixin.dao.mapper.auto;

import com.kuaizhan.kzweixin.dao.po.auto.GuideFollowPostPO;
import com.kuaizhan.kzweixin.dao.po.auto.GuideFollowPostPOExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface GuideFollowPostMapper {
    long countByExample(GuideFollowPostPOExample example);

    int deleteByExample(GuideFollowPostPOExample example);

    int deleteByPrimaryKey(Long weixinAppid);

    int insert(GuideFollowPostPO record);

    int insertSelective(GuideFollowPostPO record);

    List<GuideFollowPostPO> selectByExampleWithRowbounds(GuideFollowPostPOExample example, RowBounds rowBounds);

    List<GuideFollowPostPO> selectByExample(GuideFollowPostPOExample example);

    GuideFollowPostPO selectByPrimaryKey(Long weixinAppid);

    int updateByExampleSelective(@Param("record") GuideFollowPostPO record, @Param("example") GuideFollowPostPOExample example);

    int updateByExample(@Param("record") GuideFollowPostPO record, @Param("example") GuideFollowPostPOExample example);

    int updateByPrimaryKeySelective(GuideFollowPostPO record);

    int updateByPrimaryKey(GuideFollowPostPO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weixin_guide_follow
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int upsert(GuideFollowPostPO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weixin_guide_follow
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int upsertSelective(GuideFollowPostPO record);
}