package com.kuaizhan.kzweixin.dao.mapper.auto;

import com.kuaizhan.kzweixin.dao.po.auto.KeywordPO;
import com.kuaizhan.kzweixin.dao.po.auto.KeywordPOExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface KeywordMapper {
    long countByExample(KeywordPOExample example);

    int deleteByExample(KeywordPOExample example);

    int deleteByPrimaryKey(Long ruleId);

    int insert(KeywordPO record);

    int insertSelective(KeywordPO record);

    List<KeywordPO> selectByExampleWithBLOBsWithRowbounds(KeywordPOExample example, RowBounds rowBounds);

    List<KeywordPO> selectByExampleWithBLOBs(KeywordPOExample example);

    List<KeywordPO> selectByExampleWithRowbounds(KeywordPOExample example, RowBounds rowBounds);

    List<KeywordPO> selectByExample(KeywordPOExample example);

    KeywordPO selectByPrimaryKey(Long ruleId);

    int updateByExampleSelective(@Param("record") KeywordPO record, @Param("example") KeywordPOExample example);

    int updateByExampleWithBLOBs(@Param("record") KeywordPO record, @Param("example") KeywordPOExample example);

    int updateByExample(@Param("record") KeywordPO record, @Param("example") KeywordPOExample example);

    int updateByPrimaryKeySelective(KeywordPO record);

    int updateByPrimaryKeyWithBLOBs(KeywordPO record);

    int updateByPrimaryKey(KeywordPO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weixin_keywords
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int upsert(KeywordPO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weixin_keywords
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int upsertSelective(KeywordPO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weixin_keywords
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int upsertWithBLOBs(KeywordPO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weixin_keywords
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int upsertSelectiveWithBLOBs(KeywordPO record);
}