package com.kuaizhan.kzweixin.dao.mapper.auto;

import com.kuaizhan.kzweixin.dao.po.auto.KeywordReplyPO;
import com.kuaizhan.kzweixin.dao.po.auto.KeywordReplyPOExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;
import org.springframework.stereotype.Repository;

@Repository
public interface KeywordReplyMapper {
    long countByExample(KeywordReplyPOExample example);

    int deleteByExample(KeywordReplyPOExample example);

    int deleteByPrimaryKey(Long ruleId);

    int insert(KeywordReplyPO record);

    int insertSelective(KeywordReplyPO record);

    List<KeywordReplyPO> selectByExampleWithBLOBsWithRowbounds(KeywordReplyPOExample example, RowBounds rowBounds);

    List<KeywordReplyPO> selectByExampleWithBLOBs(KeywordReplyPOExample example);

    List<KeywordReplyPO> selectByExampleWithRowbounds(KeywordReplyPOExample example, RowBounds rowBounds);

    List<KeywordReplyPO> selectByExample(KeywordReplyPOExample example);

    KeywordReplyPO selectByPrimaryKey(Long ruleId);

    int updateByExampleSelective(@Param("record") KeywordReplyPO record, @Param("example") KeywordReplyPOExample example);

    int updateByExampleWithBLOBs(@Param("record") KeywordReplyPO record, @Param("example") KeywordReplyPOExample example);

    int updateByExample(@Param("record") KeywordReplyPO record, @Param("example") KeywordReplyPOExample example);

    int updateByPrimaryKeySelective(KeywordReplyPO record);

    int updateByPrimaryKeyWithBLOBs(KeywordReplyPO record);

    int updateByPrimaryKey(KeywordReplyPO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weixin_keywords
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int upsert(KeywordReplyPO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weixin_keywords
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int upsertSelective(KeywordReplyPO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weixin_keywords
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int upsertWithBLOBs(KeywordReplyPO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weixin_keywords
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int upsertSelectiveWithBLOBs(KeywordReplyPO record);
}