package com.kuaizhan.kzweixin.dao.mapper.auto;

import com.kuaizhan.kzweixin.dao.po.auto.MenuItemPO;
import com.kuaizhan.kzweixin.dao.po.auto.MenuItemPOExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface MenuItemMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weixin_menu_item
     *
     * @mbg.generated Tue Jun 13 19:49:06 CST 2017
     */
    long countByExample(MenuItemPOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weixin_menu_item
     *
     * @mbg.generated Tue Jun 13 19:49:06 CST 2017
     */
    int deleteByExample(MenuItemPOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weixin_menu_item
     *
     * @mbg.generated Tue Jun 13 19:49:06 CST 2017
     */
    int deleteByPrimaryKey(Long menuKey);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weixin_menu_item
     *
     * @mbg.generated Tue Jun 13 19:49:06 CST 2017
     */
    int insert(MenuItemPO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weixin_menu_item
     *
     * @mbg.generated Tue Jun 13 19:49:06 CST 2017
     */
    int insertSelective(MenuItemPO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weixin_menu_item
     *
     * @mbg.generated Tue Jun 13 19:49:06 CST 2017
     */
    List<MenuItemPO> selectByExampleWithBLOBs(MenuItemPOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weixin_menu_item
     *
     * @mbg.generated Tue Jun 13 19:49:06 CST 2017
     */
    List<MenuItemPO> selectByExample(MenuItemPOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weixin_menu_item
     *
     * @mbg.generated Tue Jun 13 19:49:06 CST 2017
     */
    MenuItemPO selectByPrimaryKey(Long menuKey);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weixin_menu_item
     *
     * @mbg.generated Tue Jun 13 19:49:06 CST 2017
     */
    int updateByExampleSelective(@Param("record") MenuItemPO record, @Param("example") MenuItemPOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weixin_menu_item
     *
     * @mbg.generated Tue Jun 13 19:49:06 CST 2017
     */
    int updateByExampleWithBLOBs(@Param("record") MenuItemPO record, @Param("example") MenuItemPOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weixin_menu_item
     *
     * @mbg.generated Tue Jun 13 19:49:06 CST 2017
     */
    int updateByExample(@Param("record") MenuItemPO record, @Param("example") MenuItemPOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weixin_menu_item
     *
     * @mbg.generated Tue Jun 13 19:49:06 CST 2017
     */
    int updateByPrimaryKeySelective(MenuItemPO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weixin_menu_item
     *
     * @mbg.generated Tue Jun 13 19:49:06 CST 2017
     */
    int updateByPrimaryKeyWithBLOBs(MenuItemPO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weixin_menu_item
     *
     * @mbg.generated Tue Jun 13 19:49:06 CST 2017
     */
    int updateByPrimaryKey(MenuItemPO record);
}