package com.kuaizhan.kzweixin.dao.mapper.auto;

import com.kuaizhan.kzweixin.dao.po.auto.MsgConfigPO;
import com.kuaizhan.kzweixin.dao.po.auto.MsgConfigPOExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface MsgConfigMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weixin_msg_config
     *
     * @mbg.generated Tue Jun 13 19:50:21 CST 2017
     */
    long countByExample(MsgConfigPOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weixin_msg_config
     *
     * @mbg.generated Tue Jun 13 19:50:21 CST 2017
     */
    int deleteByExample(MsgConfigPOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weixin_msg_config
     *
     * @mbg.generated Tue Jun 13 19:50:21 CST 2017
     */
    int deleteByPrimaryKey(Long weixinAppid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weixin_msg_config
     *
     * @mbg.generated Tue Jun 13 19:50:21 CST 2017
     */
    int insert(MsgConfigPO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weixin_msg_config
     *
     * @mbg.generated Tue Jun 13 19:50:21 CST 2017
     */
    int insertSelective(MsgConfigPO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weixin_msg_config
     *
     * @mbg.generated Tue Jun 13 19:50:21 CST 2017
     */
    List<MsgConfigPO> selectByExampleWithBLOBs(MsgConfigPOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weixin_msg_config
     *
     * @mbg.generated Tue Jun 13 19:50:21 CST 2017
     */
    List<MsgConfigPO> selectByExample(MsgConfigPOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weixin_msg_config
     *
     * @mbg.generated Tue Jun 13 19:50:21 CST 2017
     */
    MsgConfigPO selectByPrimaryKey(Long weixinAppid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weixin_msg_config
     *
     * @mbg.generated Tue Jun 13 19:50:21 CST 2017
     */
    int updateByExampleSelective(@Param("record") MsgConfigPO record, @Param("example") MsgConfigPOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weixin_msg_config
     *
     * @mbg.generated Tue Jun 13 19:50:21 CST 2017
     */
    int updateByExampleWithBLOBs(@Param("record") MsgConfigPO record, @Param("example") MsgConfigPOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weixin_msg_config
     *
     * @mbg.generated Tue Jun 13 19:50:21 CST 2017
     */
    int updateByExample(@Param("record") MsgConfigPO record, @Param("example") MsgConfigPOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weixin_msg_config
     *
     * @mbg.generated Tue Jun 13 19:50:21 CST 2017
     */
    int updateByPrimaryKeySelective(MsgConfigPO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weixin_msg_config
     *
     * @mbg.generated Tue Jun 13 19:50:21 CST 2017
     */
    int updateByPrimaryKeyWithBLOBs(MsgConfigPO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weixin_msg_config
     *
     * @mbg.generated Tue Jun 13 19:50:21 CST 2017
     */
    int updateByPrimaryKey(MsgConfigPO record);
}