package com.kuaizhan.kzweixin.dao.mapper.auto;

import com.kuaizhan.kzweixin.dao.po.auto.MsgPO;
import com.kuaizhan.kzweixin.dao.po.auto.MsgPOExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface MsgMapper {
    long countByExample(MsgPOExample example);

    int deleteByExample(MsgPOExample example);

    int deleteByPrimaryKey(Long msgId);

    int insert(MsgPO record);

    int insertSelective(MsgPO record);

    List<MsgPO> selectByExampleWithRowbounds(MsgPOExample example, RowBounds rowBounds);

    List<MsgPO> selectByExample(MsgPOExample example);

    MsgPO selectByPrimaryKey(Long msgId);

    int updateByExampleSelective(@Param("record") MsgPO record, @Param("example") MsgPOExample example);

    int updateByExample(@Param("record") MsgPO record, @Param("example") MsgPOExample example);

    int updateByPrimaryKeySelective(MsgPO record);

    int updateByPrimaryKey(MsgPO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weixin_msg_0
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int upsert(MsgPO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weixin_msg_0
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int upsertSelective(MsgPO record);
}