package com.kuaizhan.kzweixin.dao.mapper.auto;

import com.kuaizhan.kzweixin.dao.po.auto.MsgReplyPO;
import com.kuaizhan.kzweixin.dao.po.auto.MsgReplyPOExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;
import org.springframework.stereotype.Repository;

@Repository
public interface MsgReplyMapper {
    long countByExample(MsgReplyPOExample example);

    int deleteByExample(MsgReplyPOExample example);

    int deleteByPrimaryKey(Integer id);

    int insert(MsgReplyPO record);

    int insertSelective(MsgReplyPO record);

    List<MsgReplyPO> selectByExampleWithBLOBsWithRowbounds(MsgReplyPOExample example, RowBounds rowBounds);

    List<MsgReplyPO> selectByExampleWithBLOBs(MsgReplyPOExample example);

    List<MsgReplyPO> selectByExampleWithRowbounds(MsgReplyPOExample example, RowBounds rowBounds);

    List<MsgReplyPO> selectByExample(MsgReplyPOExample example);

    MsgReplyPO selectByPrimaryKey(Integer id);

    int updateByExampleSelective(@Param("record") MsgReplyPO record, @Param("example") MsgReplyPOExample example);

    int updateByExampleWithBLOBs(@Param("record") MsgReplyPO record, @Param("example") MsgReplyPOExample example);

    int updateByExample(@Param("record") MsgReplyPO record, @Param("example") MsgReplyPOExample example);

    int updateByPrimaryKeySelective(MsgReplyPO record);

    int updateByPrimaryKeyWithBLOBs(MsgReplyPO record);

    int updateByPrimaryKey(MsgReplyPO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weixin_auto_reply
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int upsert(MsgReplyPO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weixin_auto_reply
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int upsertSelective(MsgReplyPO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weixin_auto_reply
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int upsertWithBLOBs(MsgReplyPO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weixin_auto_reply
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int upsertSelectiveWithBLOBs(MsgReplyPO record);
}