package com.kuaizhan.kzweixin.dao.mapper.auto;

import com.kuaizhan.kzweixin.dao.po.auto.OpenIdPO;
import com.kuaizhan.kzweixin.dao.po.auto.OpenIdPOExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface OpenIdMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weixin_open_ids_0
     *
     * @mbg.generated Wed Jun 14 10:44:57 CST 2017
     */
    long countByExample(@Param("example") OpenIdPOExample example, @Param("tableName") String tableName);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weixin_open_ids_0
     *
     * @mbg.generated Wed Jun 14 10:44:57 CST 2017
     */
    int deleteByExample(@Param("example") OpenIdPOExample example, @Param("tableName") String tableName);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weixin_open_ids_0
     *
     * @mbg.generated Wed Jun 14 10:44:57 CST 2017
     */
    int deleteByPrimaryKey(@Param("id") Integer id, @Param("tableName") String tableName);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weixin_open_ids_0
     *
     * @mbg.generated Wed Jun 14 10:44:57 CST 2017
     */
    int insert(@Param("record") OpenIdPO record, @Param("tableName") String tableName);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weixin_open_ids_0
     *
     * @mbg.generated Wed Jun 14 10:44:57 CST 2017
     */
    int insertSelective(@Param("record") OpenIdPO record, @Param("tableName") String tableName);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weixin_open_ids_0
     *
     * @mbg.generated Wed Jun 14 10:44:57 CST 2017
     */
    List<OpenIdPO> selectByExample(@Param("example") OpenIdPOExample example, @Param("tableName") String tableName);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weixin_open_ids_0
     *
     * @mbg.generated Wed Jun 14 10:44:57 CST 2017
     */
    OpenIdPO selectByPrimaryKey(@Param("id") Integer id, @Param("tableName") String tableName);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weixin_open_ids_0
     *
     * @mbg.generated Wed Jun 14 10:44:57 CST 2017
     */
    int updateByExampleSelective(@Param("record") OpenIdPO record, @Param("example") OpenIdPOExample example, @Param("tableName") String tableName);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weixin_open_ids_0
     *
     * @mbg.generated Wed Jun 14 10:44:57 CST 2017
     */
    int updateByExample(@Param("record") OpenIdPO record, @Param("example") OpenIdPOExample example, @Param("tableName") String tableName);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weixin_open_ids_0
     *
     * @mbg.generated Wed Jun 14 10:44:57 CST 2017
     */
    int updateByPrimaryKeySelective(@Param("record") OpenIdPO record, @Param("tableName") String tableName);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weixin_open_ids_0
     *
     * @mbg.generated Wed Jun 14 10:44:57 CST 2017
     */
    int updateByPrimaryKey(@Param("record") OpenIdPO record, @Param("tableName") String tableName);
}