package com.kuaizhan.kzweixin.dao.mapper.auto;

import com.kuaizhan.kzweixin.dao.po.auto.OpenIdPO;
import com.kuaizhan.kzweixin.dao.po.auto.OpenIdPOExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface OpenIdMapper {
    long countByExample(OpenIdPOExample example);

    int deleteByExample(OpenIdPOExample example);

    int deleteByPrimaryKey(Integer id);

    int insert(OpenIdPO record);

    int insertSelective(OpenIdPO record);

    List<OpenIdPO> selectByExampleWithRowbounds(OpenIdPOExample example, RowBounds rowBounds);

    List<OpenIdPO> selectByExample(OpenIdPOExample example);

    OpenIdPO selectByPrimaryKey(Integer id);

    int updateByExampleSelective(@Param("record") OpenIdPO record, @Param("example") OpenIdPOExample example);

    int updateByExample(@Param("record") OpenIdPO record, @Param("example") OpenIdPOExample example);

    int updateByPrimaryKeySelective(OpenIdPO record);

    int updateByPrimaryKey(OpenIdPO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weixin_open_ids_0
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int upsert(OpenIdPO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weixin_open_ids_0
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int upsertSelective(OpenIdPO record);
}