package com.kuaizhan.kzweixin.dao.mapper.auto;

import com.kuaizhan.kzweixin.dao.po.auto.OpenIdPO;
import com.kuaizhan.kzweixin.dao.po.auto.OpenIdPOExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface OpenIdMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weixin_open_ids_0
     *
     * @mbg.generated Wed Jun 14 10:44:57 CST 2017
     */
    long countByExample(OpenIdPOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weixin_open_ids_0
     *
     * @mbg.generated Wed Jun 14 10:44:57 CST 2017
     */
    int deleteByExample(OpenIdPOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weixin_open_ids_0
     *
     * @mbg.generated Wed Jun 14 10:44:57 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weixin_open_ids_0
     *
     * @mbg.generated Wed Jun 14 10:44:57 CST 2017
     */
    int insert(OpenIdPO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weixin_open_ids_0
     *
     * @mbg.generated Wed Jun 14 10:44:57 CST 2017
     */
    int insertSelective(OpenIdPO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weixin_open_ids_0
     *
     * @mbg.generated Wed Jun 14 10:44:57 CST 2017
     */
    List<OpenIdPO> selectByExample(OpenIdPOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weixin_open_ids_0
     *
     * @mbg.generated Wed Jun 14 10:44:57 CST 2017
     */
    OpenIdPO selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weixin_open_ids_0
     *
     * @mbg.generated Wed Jun 14 10:44:57 CST 2017
     */
    int updateByExampleSelective(@Param("record") OpenIdPO record, @Param("example") OpenIdPOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weixin_open_ids_0
     *
     * @mbg.generated Wed Jun 14 10:44:57 CST 2017
     */
    int updateByExample(@Param("record") OpenIdPO record, @Param("example") OpenIdPOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weixin_open_ids_0
     *
     * @mbg.generated Wed Jun 14 10:44:57 CST 2017
     */
    int updateByPrimaryKeySelective(OpenIdPO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weixin_open_ids_0
     *
     * @mbg.generated Wed Jun 14 10:44:57 CST 2017
     */
    int updateByPrimaryKey(OpenIdPO record);
}