package com.kuaizhan.kzweixin.dao.mapper.auto;

import com.kuaizhan.kzweixin.dao.po.auto.QrcodePO;
import com.kuaizhan.kzweixin.dao.po.auto.QrcodePOExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface QrcodeMapper {
    long countByExample(QrcodePOExample example);

    int deleteByExample(QrcodePOExample example);

    int deleteByPrimaryKey(Long qrcodeId);

    int insert(QrcodePO record);

    int insertSelective(QrcodePO record);

    List<QrcodePO> selectByExampleWithBLOBsWithRowbounds(QrcodePOExample example, RowBounds rowBounds);

    List<QrcodePO> selectByExampleWithBLOBs(QrcodePOExample example);

    List<QrcodePO> selectByExampleWithRowbounds(QrcodePOExample example, RowBounds rowBounds);

    List<QrcodePO> selectByExample(QrcodePOExample example);

    QrcodePO selectByPrimaryKey(Long qrcodeId);

    int updateByExampleSelective(@Param("record") QrcodePO record, @Param("example") QrcodePOExample example);

    int updateByExampleWithBLOBs(@Param("record") QrcodePO record, @Param("example") QrcodePOExample example);

    int updateByExample(@Param("record") QrcodePO record, @Param("example") QrcodePOExample example);

    int updateByPrimaryKeySelective(QrcodePO record);

    int updateByPrimaryKeyWithBLOBs(QrcodePO record);

    int updateByPrimaryKey(QrcodePO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weixin_qrcode
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int upsert(QrcodePO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weixin_qrcode
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int upsertSelective(QrcodePO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weixin_qrcode
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int upsertWithBLOBs(QrcodePO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weixin_qrcode
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int upsertSelectiveWithBLOBs(QrcodePO record);
}