package com.kuaizhan.kzweixin.dao.mapper.auto;

import com.kuaizhan.kzweixin.pojo.po.auto.WeixinMsgConfig;
import com.kuaizhan.kzweixin.pojo.po.auto.WeixinMsgConfigExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface WeixinMsgConfigMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weixin_msg_config
     *
     * @mbggenerated Tue May 16 17:13:45 CST 2017
     */
    int countByExample(WeixinMsgConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weixin_msg_config
     *
     * @mbggenerated Tue May 16 17:13:45 CST 2017
     */
    int deleteByExample(WeixinMsgConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weixin_msg_config
     *
     * @mbggenerated Tue May 16 17:13:45 CST 2017
     */
    int deleteByPrimaryKey(Long weixinAppid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weixin_msg_config
     *
     * @mbggenerated Tue May 16 17:13:45 CST 2017
     */
    int insert(WeixinMsgConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weixin_msg_config
     *
     * @mbggenerated Tue May 16 17:13:45 CST 2017
     */
    int insertSelective(WeixinMsgConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weixin_msg_config
     *
     * @mbggenerated Tue May 16 17:13:45 CST 2017
     */
    List<WeixinMsgConfig> selectByExampleWithBLOBs(WeixinMsgConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weixin_msg_config
     *
     * @mbggenerated Tue May 16 17:13:45 CST 2017
     */
    List<WeixinMsgConfig> selectByExample(WeixinMsgConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weixin_msg_config
     *
     * @mbggenerated Tue May 16 17:13:45 CST 2017
     */
    WeixinMsgConfig selectByPrimaryKey(Long weixinAppid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weixin_msg_config
     *
     * @mbggenerated Tue May 16 17:13:45 CST 2017
     */
    int updateByExampleSelective(@Param("record") WeixinMsgConfig record, @Param("example") WeixinMsgConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weixin_msg_config
     *
     * @mbggenerated Tue May 16 17:13:45 CST 2017
     */
    int updateByExampleWithBLOBs(@Param("record") WeixinMsgConfig record, @Param("example") WeixinMsgConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weixin_msg_config
     *
     * @mbggenerated Tue May 16 17:13:45 CST 2017
     */
    int updateByExample(@Param("record") WeixinMsgConfig record, @Param("example") WeixinMsgConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weixin_msg_config
     *
     * @mbggenerated Tue May 16 17:13:45 CST 2017
     */
    int updateByPrimaryKeySelective(WeixinMsgConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weixin_msg_config
     *
     * @mbggenerated Tue May 16 17:13:45 CST 2017
     */
    int updateByPrimaryKeyWithBLOBs(WeixinMsgConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weixin_msg_config
     *
     * @mbggenerated Tue May 16 17:13:45 CST 2017
     */
    int updateByPrimaryKey(WeixinMsgConfig record);
}