package com.kuaizhan.kzweixin.dao.mapper.auto;

import com.kuaizhan.kzweixin.dao.po.auto.WeixinConditionalMenu;
import com.kuaizhan.kzweixin.dao.po.auto.WeixinConditionalMenuExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface WeixinConditionalMenuMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weixin_conditional_menu
     *
     * @mbggenerated Mon Jun 05 16:22:07 CST 2017
     */
    int countByExample(WeixinConditionalMenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weixin_conditional_menu
     *
     * @mbggenerated Mon Jun 05 16:22:07 CST 2017
     */
    int deleteByExample(WeixinConditionalMenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weixin_conditional_menu
     *
     * @mbggenerated Mon Jun 05 16:22:07 CST 2017
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weixin_conditional_menu
     *
     * @mbggenerated Mon Jun 05 16:22:07 CST 2017
     */
    int insert(WeixinConditionalMenu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weixin_conditional_menu
     *
     * @mbggenerated Mon Jun 05 16:22:07 CST 2017
     */
    int insertSelective(WeixinConditionalMenu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weixin_conditional_menu
     *
     * @mbggenerated Mon Jun 05 16:22:07 CST 2017
     */
    List<WeixinConditionalMenu> selectByExampleWithBLOBs(WeixinConditionalMenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weixin_conditional_menu
     *
     * @mbggenerated Mon Jun 05 16:22:07 CST 2017
     */
    List<WeixinConditionalMenu> selectByExample(WeixinConditionalMenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weixin_conditional_menu
     *
     * @mbggenerated Mon Jun 05 16:22:07 CST 2017
     */
    WeixinConditionalMenu selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weixin_conditional_menu
     *
     * @mbggenerated Mon Jun 05 16:22:07 CST 2017
     */
    int updateByExampleSelective(@Param("record") WeixinConditionalMenu record, @Param("example") WeixinConditionalMenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weixin_conditional_menu
     *
     * @mbggenerated Mon Jun 05 16:22:07 CST 2017
     */
    int updateByExampleWithBLOBs(@Param("record") WeixinConditionalMenu record, @Param("example") WeixinConditionalMenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weixin_conditional_menu
     *
     * @mbggenerated Mon Jun 05 16:22:07 CST 2017
     */
    int updateByExample(@Param("record") WeixinConditionalMenu record, @Param("example") WeixinConditionalMenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weixin_conditional_menu
     *
     * @mbggenerated Mon Jun 05 16:22:07 CST 2017
     */
    int updateByPrimaryKeySelective(WeixinConditionalMenu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weixin_conditional_menu
     *
     * @mbggenerated Mon Jun 05 16:22:07 CST 2017
     */
    int updateByPrimaryKeyWithBLOBs(WeixinConditionalMenu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weixin_conditional_menu
     *
     * @mbggenerated Mon Jun 05 16:22:07 CST 2017
     */
    int updateByPrimaryKey(WeixinConditionalMenu record);
}